resource "aws_s3_bucket" "drive" {
  bucket = "nova-drive-caringal"

  tags = {
    Environment = var.environment
    Purpose     = "novadrive-file-storage"
  }
}

resource "aws_s3_bucket_public_access_block" "drive" {
  bucket                  = aws_s3_bucket.drive.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_cors_configuration" "drive" {
  bucket = aws_s3_bucket.drive.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST", "DELETE", "HEAD"]
    allowed_origins = ["https://${var.custom_domain}"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}

# Lifecycle: deletion by lifecycle is explicitly prohibited for user files.
# NEVER add an expiration{} block for user data here.
# Files are only deleted by explicit user action through the app (drive_delete view).
#
# NOTE: the old blanket "auto-tiering" rule was removed — the app already sets
# GLACIER_IR on user files at upload (confirm_upload), and blanket tiering
# would push thumbs/ into Glacier, reintroducing retrieval fees on every
# grid load. Thumbnails must stay in STANDARD.
resource "aws_s3_bucket_lifecycle_configuration" "drive" {
  bucket = aws_s3_bucket.drive.id

  # Expire incomplete multipart uploads after 7 days to avoid orphaned storage charges.
  # This only removes partial uploads that were never completed — not actual files.
  rule {
    id     = "abort-incomplete-multipart"
    status = "Enabled"

    filter {}

    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  # Auto-delete temp zips generated for folder downloads — 24h is plenty.
  # These are never user files; they're generated by the batch worker.
  rule {
    id     = "expire-temp-zips"
    status = "Enabled"

    filter {
      prefix = "temp-zips/"
    }

    expiration {
      days = 1
    }
  }
}

# S3 event notifications — one resource holds ALL notifications for the bucket
resource "aws_s3_bucket_notification" "drive_restore_completed" {
  bucket = aws_s3_bucket.drive.id

  # Glacier restore finished → email the user
  lambda_function {
    lambda_function_arn = aws_lambda_function.notify.arn
    events              = ["s3:ObjectRestore:Completed"]
  }

  # New object uploaded → generate WebP thumbnail
  # (thumbnailer ignores thumbs/, temp-zips/, static/ so it can't recurse)
  lambda_function {
    lambda_function_arn = aws_lambda_function.thumbnailer.arn
    events              = ["s3:ObjectCreated:*"]
  }

  depends_on = [
    aws_lambda_permission.s3_invoke_notify,
    aws_lambda_permission.s3_invoke_thumbnailer,
  ]
}

# Only CloudFront (via OAC) can read objects — no direct S3 access
resource "aws_s3_bucket_policy" "drive" {
  bucket = aws_s3_bucket.drive.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AllowCloudFrontOAC"
        Effect = "Allow"
        Principal = {
          Service = "cloudfront.amazonaws.com"
        }
        Action   = "s3:GetObject"
        Resource = "${aws_s3_bucket.drive.arn}/*"
        Condition = {
          StringEquals = {
            "AWS:SourceArn" = aws_cloudfront_distribution.drive.arn
          }
        }
      },
    ]
  })

  depends_on = [aws_cloudfront_distribution.drive]
}

resource "aws_s3_object" "logo_ico" {
  bucket       = aws_s3_bucket.drive.bucket
  key          = "static/img/novadrivelogo.ico"
  source       = "${path.module}/documentation images/novadrivelogo.ico"
  content_type = "image/x-icon"
  etag         = filemd5("${path.module}/documentation images/novadrivelogo.ico")
}

resource "aws_s3_object" "logo_png" {
  bucket       = aws_s3_bucket.drive.bucket
  key          = "static/img/novadrivelogo.png"
  source       = "${path.module}/documentation images/novadrivelogo.png"
  content_type = "image/png"
  etag         = filemd5("${path.module}/documentation images/novadrivelogo.png")
}
