from django.urls import path
from . import views

urlpatterns = [
    path("",                                views.drive_home,              name="drive_home"),
    # Literal routes must precede the <str:folder_pk> wildcard — unlike the old
    # <int:> converter, <str:> matches "create" and would shadow it.
    path("folder/create/",                  views.create_folder,           name="drive_create_folder"),
    path("folder/<str:folder_pk>/",         views.drive_home,              name="drive_folder"),
    path("folder/<str:pk>/delete/",         views.delete_folder,           name="drive_delete_folder"),
    path("folder/<str:pk>/rename/",         views.rename_folder,           name="drive_rename_folder"),
    path("file/<str:pk>/rename/",           views.rename_file,             name="drive_rename_file"),
    path("upload-url/",                     views.upload_url,              name="drive_upload_url"),
    path("confirm/",                        views.confirm_upload,          name="drive_confirm"),
    path("multipart/create/",               views.multipart_create,        name="drive_multipart_create"),
    path("multipart/urls/",                 views.multipart_urls,          name="drive_multipart_urls"),
    path("multipart/complete/",             views.multipart_complete,      name="drive_multipart_complete"),
    path("multipart/abort/",                views.multipart_abort,         name="drive_multipart_abort"),
    path("storage/",                        views.storage_stats,           name="drive_storage"),
    path("download/<str:pk>/",              views.download_file,           name="drive_download"),
    path("view/<str:pk>/url/",              views.get_file_url,            name="drive_file_url"),
    path("view/<str:pk>/",                  views.view_file,               name="drive_view"),
    path("thumb/<str:pk>/",                 views.file_thumbnail,          name="drive_thumb"),
    path("delete/<str:pk>/",               views.delete_file,             name="drive_delete"),
    path("bulk-delete/",                    views.bulk_delete,             name="drive_bulk_delete"),
    path("archive/",                        views.archive_files,           name="drive_archive"),
    path("archive/view/",                   views.archive_view,            name="drive_archive_view"),
    path("restore/<str:pk>/",              views.restore_file,            name="drive_restore"),
    path("restore/",                        views.bulk_restore,            name="drive_bulk_restore"),
    path("bin/",                            views.recycle_bin,             name="drive_bin"),
    path("bin/<str:pk>/restore/",          views.restore_from_bin,        name="drive_bin_restore"),
    path("bin/<str:pk>/delete/",           views.permanent_delete,        name="drive_bin_delete"),
    path("bin/folder/<str:pk>/restore/",   views.restore_folder_from_bin, name="drive_bin_folder_restore"),
    path("bin/bulk-restore/",              views.bulk_bin_restore,        name="drive_bin_bulk_restore"),
    path("bin/bulk-delete/",               views.bulk_bin_delete,         name="drive_bin_bulk_delete"),
    path("folder/<str:pk>/zip/",           views.zip_folder,              name="drive_zip_folder"),
    path("folders/zip/",                   views.zip_folder,              name="drive_zip_folders"),
    path("job/<str:job_id>/status/",       views.job_status,              name="drive_job_status"),
    path("timeline/",                       views.timeline_view,           name="drive_timeline"),
    path("failed/",                         views.failed_uploads,          name="drive_failed"),
    path("failed/record/",                  views.record_upload_failure,   name="drive_failed_record"),
    path("failed/delete/",                  views.delete_upload_failures,  name="drive_failed_delete"),
]
